version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "monthly"
  commit-message:
    prefix: chore
    prefix-development: chore
    include: scope
  groups:
    actions-deps:
      patterns:
        - "*"  groups:
    actions-deps:
      patterns:
        - "*"
# Go mod bot configurations
- package-ecosystem: "pip"
  directory: "/docker"
  schedule:
    interval: "monthly"
  open-pull-requests-limit: 10
  commit-message:
    prefix: chore
    prefix-development: chore
    include: scope
# Docker bot configurations
- package-ecosystem: "docker"
  directories:
  - "/docker"
  schedule:
    interval: "monthly"
  commit-message:
    prefix: chore
    prefix-development: chore
    include: scope
